# Stores information about a ray-surface intersection. This information 
# is typically used for shading.



class HitRecord
  ##
  # :attr_accessor: 
  #   position: Vector3f
  #     position where the ray hit the surface
  #
  #   normal: Vector3f
  #     normal at hit pos
  #
  #   t1,t2: Vector3f
  #     tangent and bitangent at hit pos
  #
  #   u,v: vector2f
  #     texture coordinates
  #
  #   w: Vector3f
  #     Direction towards origin of ray that hit surface. 
  #     By convention it points away from the surface, 
  #     that is, in the direction opposite to the incident ray.
  #
  #   t: Float 
  #     parameter of the ray at the hit point
  #
  #   material: Material
  #     The material at the hit point.
  #
  #   p: Float
  #     Area probability density. 
  #     This is typically used when a hit record is 
  #     generated by sampling the geometry, 
  #     like in implementations of LightGeometry
  # 
  #   tbs: Matrix3f
  #     tangent space transformation 
  
  attr_accessor :position,
                :normal,
                :t1, :t2,
                :u, :v,
                :w,
                :t,
                :intersectable,
                :material,
                :p,
                :tbs
end